### ISSUE TITLE
About 'Permission denied' when testing zonefs.

### ISSUE THREAD

**Issue by yigexintaibuhaoderen** [westerndigitalcorporation/zonefs-tools#3]
"Hello, I encountered some issues while using ZoneFS on Ubuntu system based on Linux 5.15, and I hope to seek some advice. Firstly, I created a virtual block device `nullb0` using the `zbd Tool`, and then used `zonefs-tool` to create ZoneFS on `nullb0`, which was subsequently mounted to the directory `/mnt/zonefs`. However, I can only perform write tests using the `dd` command. When I attempt to use testing tools like `fio` or `filebench` on `/mnt/zonefs`, I encounter permission denied errors and cannot gain write permissions. Even attempts to modify permissions using commands like `chmod` have been unsuccessful. Could you please advise me on how to conduct performance testing using testing tools?"

**Comment by damien-lemoal** [comment]
"using the zbd tool" -> I do not understand what that is. Creating a zoned null_blk device can be done either through modprobe or using configfs...

For zonefs, by default, all zone files are created belonging to the root user (UID=GID=0). If you want to create the files belonging to another user, use the uid= and gid= options of mkzonefs (or mkfs.zonefs). See "man mkzonefs" for details.

You can also use chown to change the UID and GID of individual zone files, with sudo if needed. But beware that this change is not persistent and will be lost after umount/mount.

**Comment by yigexintaibuhaoderen** [comment]
Thank you for your help, but I am still experiencing issues. The details of the created ZoneFS are as follows:
```
/dev/nullb0: 1048576 512-byte sectors (0 GiB)
  Host-managed device
  16 zones of 65536 512-byte sectors (32 MiB)
  4 conventional zones, 12 sequential zones
  0 read-only zones, 0 offline zones
Format:
  15 usable zones
  Aggregate conventional zones: disabled
  File UID: 0
  File GID: 0
  File access permissions: 777
  FS UUID: 88ae8a06-7c2c-41f9-8f5a-a2794b4ad38e
Resetting sequential zones
Writing super block
```

I used the following command to mount it:
`sudo mount -t zonefs /dev/nullb0 /mnt/zonefs`

And I am operating under the root user:
```
root@ubuntu:/home/yfx# id
uid=0(root) gid=0(root) groups=0(root)
```

The directory permissions after mounting are as follows:
```
ls -ld /mnt/zonefs
dr-xr-xr-x 4 root root 2 Jun  5 19:35 /mnt/zonefs
root@ubuntu:/home/yfx# ls -ld /mnt/zonefs/seq
dr-xr-xr-x 2 root root 12 Jun  5 19:35 /mnt/zonefs/seq
root@ubuntu:/home/yfx# ls -ld /mnt/zonefs/seq/0
-rwxrwxrwx 1 root root 0 Jun  5 19:35 /mnt/zonefs/seq/0
```

However, I am unable to change the permissions of /mnt/zonefs:
```
root@ubuntu:/home/yfx# chmod 777 /mnt/zonefs
chmod: changing permissions of '/mnt/zonefs': Operation not permitted
```

When I use the fio command to test:
`sudo fio --directory=/mnt/zonefs --iodepth=1 --ioengine=libaio --direct=1 --rw=write --bs=4k --size=300m --numjobs=1 --runtime=3000 --group_reporting --name=test-write --allow_mounted_write=1 --zonemode=zbd --zonesize=32M`
I get the following error:
```
test-write: (g=0): rw=write, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=1
fio-3.16
Starting 1 process
test-write: Laying out IO file (1 file / 300MiB)
fio: pid=0, err=13/file:filesetup.c:162, func=open, error=Permission denied
```

However, when I use dd, it works normally:
```
dd if=/dev/nullb0 of=/mnt/zonefs/seq/0 bs=4096 count=1 conv=notrunc oflag=direct
1+0 records in
1+0 records out
4096 bytes (4.1 kB, 4.0 KiB) copied, 8.8616e-05 s, 46.2 MB/s
```

Could you please advise on how I can use testing tools to conduct performance testing under these circumstances?

**Comment by damien-lemoal** [comment]
For fio, you need to specify a zone file name. Otherwise, fio will try to create a file in the directory /mnt/zonefs which is not allowed with zonefs. See the use of fio in the test scripts in zonefs-tools/tests/scripts as examples.

As for the failure of chmod, this is because you are trying to make the directory writable. That is not allowed with zonefs because files and sub-directories cannot be created. So you can only change the r and x attributes.

**Comment by yigexintaibuhaoderen** [comment]
> For fio, you need to specify a zone file name. Otherwise, fio will try to create a file in the directory /mnt/zonefs which is not allowed with zonefs. See the use of fio in the test scripts in zonefs-tools/tests/scripts as examples.
> 
> As for the failure of chmod, this is because you are trying to make the directory writable. That is not allowed with zonefs because files and sub-directories cannot be created. So you can only change the r and x attributes.

ok,I got it.Thank you so much.
