### ISSUE TITLE
About GC in zonefs.

### ISSUE THREAD

**Issue by yigexintaibuhaoderen** [westerndigitalcorporation/zonefs-tools#4]
Could you please explain how ZoneFS manages and reclaims dirty data? It appears that there is no garbage collection process.

**Comment by damien-lemoal** [comment]
I think you are misunderstanding zonefs design goal. zonefs is NOT a POSIX file system and data written in sequential files cannot be overwritten unless the file is truncated to 0 first (all data deleted). So there is absolutely no need for internal GC.
If you application using zonefs needs GC, then it should implement it. That is not zonefs job to do it.

Please read carefully Documentation/filesystems/zonefs.rst, especially the Introduction section. With that, I think you will understand that your question makes no sense at all.
